### ISSUE TITLE
Deleting questions throws key constraint errors.

### ISSUE THREAD

**Issue by net8floz** [codewizardshq/code-challenge#15]
When I try q del or q replace with existing answers they at a point become un-deletable. 

Steps to reproduce look something like add a question, replace the question multiple times changing answers and title fields. 

Expected is for no errors and for all relationships to be stomped and and the entities deleted. 

Error received: 
```
sqlalchemy.exc.IntegrityError: (MySQLdb._exceptions.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`code_challenge_local`.`answer`, CONSTRAINT `answer_ibfk_1` FOREIGN KEY (`question_id`) REFERENCES `question` (`id`))')
[SQL: DELETE FROM question WHERE question.id = %s]
[parameters: (8,)]
```

**Comment by usrbinsam** [comment]
Fixed here: https://github.com/codewizardshq/code-challenge/commit/044617fbf48cd7677335b5a27d95528dbdf13603
